anaconda_project/test/test_project_file.py, anaconda_project/yaml_file.py
=> Use block-style formatting for lists in default anaconda-project.yml

anaconda_project/commands/prepare_with_mode.py, anaconda_project/commands/test/test_prepare.py
this was just confusing and weird to do.
Fixes #19
=> Don't interactively prompt for CONDA_PREFIX

anaconda_project/project.py, anaconda_project/test/test_project.py
This allows the server to special-case certain versions
=> Upload anaconda_project_version in publication_info()

anaconda_project/commands/test/test_bundle.py, anaconda_project/internal/test/tmpfile_utils.py, anaconda_project/project.py, anaconda_project/project_file.py, anaconda_project/test/test_prepare.py, anaconda_project/test/test_project.py, anaconda_project/test/test_project_file.py
=> Make the name field mandatory

anaconda_project/project_commands.py, anaconda_project/test/test_project.py, docs/source/reference.rst, examples/quote_api/anaconda-project.yml, examples/quote_api/quote.py
This specifies the ip to listen on (bokeh --address, jupyter --ip)
Fixes #12 
Non-bokeh/notebook examples will have to be updated.
=> Support an --anaconda-project-address command line option

examples/stocks/anaconda-project.yml, examples/stocks/main.py
Use "." not "main.py" to avoid warning, copy new code
from Bokeh's examples directory to adapt to latest API.
=> Update examples/stocks to Bokeh 0.12.4

anaconda_project/project.py, anaconda_project/yaml_file.py
format yaml more nicely, and don't let nonfatal suggestions break creating environments
=> Couple of small fixes

anaconda_project/project_ops.py
At the moment not actually using this, but happened to do the work, so.
=> Generalize modify_platforms to be able to modify other field names

MANIFEST.in
=> Add LICENSE to manifest

CONTRIBUTING.md
To save people the confusion I experienced :-)
=> Add yapf pin warning

anaconda_project/internal/cli/project_load.py, anaconda_project/internal/cli/test/test_bundle.py, anaconda_project/internal/cli/test/test_project_load.py, anaconda_project/project.py, anaconda_project/test/test_api.py
Supercedes #88. Uses the standard project problem mechanism to interactively handle the nonexistence of a project file.
=> Handle nonexistent project file

anaconda_project/api.py, anaconda_project/client.py, anaconda_project/internal/cli/main.py, anaconda_project/internal/cli/test/test_bug_handler.py, anaconda_project/internal/cli/test/test_main.py, anaconda_project/internal/cli/upload.py, anaconda_project/internal/test/test_streaming_popen.py, anaconda_project/project_ops.py, anaconda_project/test/test_api.py, anaconda_project/test/test_project.py
Add "--private" flag to upload command. This will set the access to private.
=> Upload private

anaconda_project/env_spec.py, anaconda_project/local_state_file.py, anaconda_project/project_file.py, anaconda_project/project_lock_file.py, anaconda_project/test/test_project_lock_file.py, anaconda_project/yaml_file.py
Don't let the branch name fool you; this is purely a bit of cleanup around ruamel.yaml imports and default yaml files.
=> yaml processing refactor and cleanup

anaconda_project/project.py, anaconda_project/test/test_project.py
=> User fields

anaconda_project/internal/cli/main.py, anaconda_project/internal/cli/prepare.py, anaconda_project/internal/cli/test/test_prepare.py
=> Prepare update env

.travis.yml, anaconda_project/internal/test/tmpfile_utils.py, conda.recipe/meta.yaml
Trying to figure out why Mac OSX / Python 3.7 fails spectacularly in Travis but not locally
=> Correct failing tests on OSX / Python 3.7

anaconda_project/project.py
Fixes #255. Touching the `yaml_dict` seems to cause the `anaconda-project.yml` to get rewritten/formatted.
=> Fix for issue #255 when using user_fields

.github/workflows/main.yml
Use the conda-pack pattern to upload the built package and the docs.
=> add support for uploading package

docs/source/config.rst, docs/source/index.rst
Added a section in the docs about `ANACONDA_PROJECT_ENVS_PATH`.
=> Add documentation about ANACONDA_PROJECT_ENVS_PATH

CHANGELOG.md
@mcg1969 , does this look right?
=> update changelog for 0.9.0 and 0.9.1

.gitignore, CHANGELOG.md, anaconda_project/cli.py, docs/source/index.rst, docs/source/user-guide/tasks/create-project-archive.rst, docs/source/user-guide/tasks/create-project.rst, docs/source/user-guide/tasks/docker-image.rst, docs/source/user-guide/tasks/work-with-packages.rst, setup.cfg
This PR updates the changelog and does some minor maintenance before releasing the next version
=> Release 0.10

anaconda_project/internal/http_client.py, conda.recipe/meta.yaml
Try it for yourself and let me know your experiences:
```
conda install -c defusco/label/dev anaconda-project=0.10.0+1
```
=> tqdm progress for downloads

.github/workflows/main.yml, CHANGELOG.md, anaconda_project/internal/http_client.py
Fixes #339 
I have seen no existing infrastructure for testing this sort of thing. I tested it on the example reported in the issue and the fix worked fine.
=> Check if there is a progress bar before updating it

docs/source/conf.py
This reference to the custom.css in conf.py should ensure it overwrites the main theme.
=> Conf fix, part 2

docs/source/conf.py, docs/source/index.rst, docs/source/user-guide/getting-started.rst
Updates the quick start guide to walk through running the hvplot interactive demo. Adds a new link to quick start from the documentation homepage.
=> Update Quick start guide

docs/source/conf.py, docs/source/getting-started.rst, docs/source/index.rst, docs/source/user-guide/index.rst, docs/source/user-guide/reference.rst
Also manually updated copyright date.
=> Improved Getting Started and moved up in TOC.
