anaconda_project/commands/test/test_bundle.py, anaconda_project/commands/test/test_clean.py, anaconda_project/commands/test/test_command_commands.py, anaconda_project/commands/test/test_download_commands.py, anaconda_project/commands/test/test_environment_commands.py, anaconda_project/commands/test/test_project_load.py, anaconda_project/commands/test/test_service_commands.py, anaconda_project/commands/test/test_upload.py, anaconda_project/commands/test/test_variable_commands.py, anaconda_project/project.py, anaconda_project/test/test_prepare.py, anaconda_project/test/test_project.py, anaconda_project/test/test_project_ops.py, anaconda_project/yaml_file.py
Problems now have properties:
* maybe_line (line number or None)
* maybe_column (column number or None)
* maybe_filename (filename with the problem, or None)
* text_without_filename (the problem.text minus filename in front if normally there would be one)
cc @goanpeca
=> Add line numbers to syntax errors, and filename info to problems

anaconda_project/commands/test/test_environment_commands.py, anaconda_project/env_spec.py, anaconda_project/project_file.py, anaconda_project/project_ops.py, anaconda_project/test/test_env_spec.py, anaconda_project/test/test_project_file.py
The main thing here is to close #20 by using global `packages:` instead of env-spec-specific `packages:` by default. Fixed a few other things I found along the way too.
=> Improvements to the default anaconda-project.yml

anaconda_project/archiver.py, anaconda_project/commands/project_load.py, anaconda_project/commands/test/test_bundle.py, anaconda_project/internal/test/tmpfile_utils.py, anaconda_project/test/test_project.py, anaconda_project/test/test_project_ops.py, anaconda_project/test/test_yaml_file.py, anaconda_project/yaml_file.py
There's also a change in here to make empty project files invalid, instead of implicitly assuming they have default project file contents.
Should fix #11 (by returning a failed status from the upload function).
=> Disallow archiving/uploading projects without a project file

.travis.yml, anaconda_project/internal/test/test_conda_api.py, anaconda_project/internal/test/test_default_conda_manager.py
Also, only test one python version on OS X, not all of them.
Don't think OS X has ever failed even once when Linux passed,
so no need to waste so many jobs.
=> Test against multiple conda versions

anaconda_project/commands/test/test_command_commands.py, anaconda_project/internal/notebook_analyzer.py, anaconda_project/internal/test/test_notebook_analyzer.py, anaconda_project/project.py, anaconda_project/project_commands.py, anaconda_project/project_ops.py, anaconda_project/test/test_project.py, anaconda_project/test/test_project_ops.py, docs/source/reference.rst, setup.py
There are a couple of TODO I put in here for pre-existing limitations that should be cleaned up,
but don't want to do those in this PR.
One thing about this, it will not add the `registers_fusion_function` if `@fusion.register` is added to a notebook _after_ the notebook is already in anaconda-project.yml. At that point people would have to add the `details: { registers_fusion_function: true }` line themselves.
cc @fpliger
=> Add registers_fusion_function:true if a notebook contains @fusion.register

anaconda_project/plugins/requirement.py, anaconda_project/plugins/test/test_requirement.py, anaconda_project/project.py, anaconda_project/test/test_project.py
If the default is None/missing we leave it out of the JSON.
We canonicalize the default to a string, even if it was an int
or float in anaconda-project.yml, so the server side doesn't have
to deal with that.
Also did a little DRY cleanup in publication_info() across the
requirement types. This leads to supplying encrypted=False for
downloads and services, but that seems fine.
=> Include "default" for variables in publication_info()

anaconda_project/api.py, anaconda_project/archiver.py, anaconda_project/env_spec.py, anaconda_project/internal/cli/download_commands.py, anaconda_project/internal/cli/main.py, anaconda_project/internal/cli/prepare_with_mode.py, anaconda_project/internal/cli/service_commands.py, anaconda_project/internal/cli/test/test_download_commands.py, anaconda_project/internal/cli/test/test_prepare.py, anaconda_project/internal/cli/test/test_variable_commands.py, anaconda_project/internal/cli/variable_commands.py, anaconda_project/internal/test/test_ui_server.py, anaconda_project/plugins/registry.py, anaconda_project/plugins/requirement.py, anaconda_project/plugins/requirements/download.py, anaconda_project/plugins/requirements/service.py, anaconda_project/plugins/requirements/test/test_download_requirement.py, anaconda_project/plugins/requirements/test/test_service_requirement.py, anaconda_project/plugins/test/test_provider.py, anaconda_project/prepare.py, anaconda_project/project.py, anaconda_project/project_ops.py, anaconda_project/test/test_api.py, anaconda_project/test/test_prepare.py, anaconda_project/test/test_project.py, anaconda_project/test/test_project_ops.py
This is for #52 
This will be a breaking change, both API/JSON-wise and semantically.
=> Move variables/services/downloads to be per-env-spec

anaconda_project/conda_manager.py, anaconda_project/project.py, anaconda_project/project_ops.py, anaconda_project/test/test_project_ops.py
This makes `anaconda-project lock` create lock sets for env specs that
lack them, like `anaconda-project update`. This may "do what I mean"
if I manually add an env spec and then try to lock it.
=> Special-case missing lock sets in lock file, update them when locking

anaconda_project/internal/conda_api.py, anaconda_project/internal/test/test_conda_api.py
This allows conda to be resolved as a dependency, in case
there is an environment spec that depends on it. That environment
will still fail to install unless it *also* starts with an
underscore.
=> conda: resolve using an underscore prefixed environment

anaconda_project/internal/plugins.py, anaconda_project/plugins.py, anaconda_project/project.py, anaconda_project/project_commands.py, anaconda_project/test/test_plugins.py, anaconda_project/test/test_project_ops.py
This partially implements #89  (at lease for packaged command plugins).
This is a second pass on #94, trimming everything related to "drop in" plugins and just keeping a clean PR for plugins registered using entry_points.
=> Command Plugins 

.travis.yml, anaconda_project/internal/test/test_conda_api.py, anaconda_project/internal/test/test_default_conda_manager.py, anaconda_project/internal/test/test_pip_api.py, appveyor.yml, setup.py
Ok @fpliger after several different attempts, I these changes fix all the failing tests and update a bit the CI configuration to move into a direction where we can update to the latest conda more easily.
Many tests are currently failing with conda-canary, and about 3 or 4 fail with latest conda. The next PR will aim to use latest conda and fix failing tests. After that, we should fix all failing things with conda-canary (see #126) .
Any comments @fpliger or is this good to merge? (*only the OSX container on travis has not finished due to the travis queue backlog...* we could disable that container to make our dev process a bit more streamlined, and only run when on master, which means when the PR is merged)  
----
:-)
=> PR: Update/test conda

anaconda_project/project_ops.py, anaconda_project/test/test_bundler.py, anaconda_project/test/test_project_ops.py
During an attempt to create a project from an AENv4 project I noticed that it scanned `.ipynb_checkpoints` directories that were not in the project root. It seems safe to avoid doing this.
=> Ignore all ipynb_checkpoints directories

anaconda_project/internal/cli/test/test_project_load.py, anaconda_project/project.py, anaconda_project/test/test_project.py
Go to `examples/stocks` and remove the `env_specs` section from the YAML file. This will cause an error like this:
```
$ anaconda-project prepare
An unexpected error occurred, most likely a bug in anaconda-project.
(The error was: KeyError: None)
Details about the error were saved to /var/folders/nx/cwnch48d6l30h8sf79t598mh0000gp/T/bug_details_anaconda-project_2018-12-07_g98rau6e.txt
```
What you should get is something like this:
```
$ anaconda-project prepare
anaconda-project.yml: The env_specs section is empty.
Add an environment spec to anaconda-project.yml? 
```
This fixes that, by allowing `_verify_command_requirements` to silently fail if the command environment is entirely missing. That fact is detected elsewhere so nothing is lost by doing so.
=> avoid crash in prepare/update if env_specs is missing

anaconda_project/plugins.py, anaconda_project/project_commands.py, anaconda_project/test/test_plugins.py, anaconda_project/test/test_project.py
As currently implemented, the `supports_http_options` flag has no useful impact.
For notebooks and bokeh apps, `supports_http_options` defaults to `true`, which allows the code to translate these options to a form that these types of applications can understand. Overriding this default, and setting `supports_http_options` to `false`, would break both of these apps. It would be better therefore if this option is not available for these cases.
On the other hand, for scripts (e.g., `windows` and `unix`), the flag has no effect whatsoever. If the HTTP options are passed to an `anaconda-project run` command, they are passed through unchanged, no matter what the value of this setting is.
This simple PR solves the second case, but not the first. It causes `anaconda-project` to properly respect …
=> Honor supports_http_options: false by dropping them when found

anaconda_project/project_commands.py, anaconda_project/test/test_project_commands.py
Fixes #154.
Rebases #158; original text from there:
-------
Not sure how this made it through this long, but the current behavior is a pretty awful experience: random interleaved outputs (#154), broken usage when scripted, and failures not being caught.
Can work up a proper test if necessary... basically a project file like:
```yaml
commands:
a:
windows: timeout 1 && echo a
b:
windows: echo b
```
then
```bat
anaconda-project run a
anaconda-project run b
```
would yield
```
b # immediately
a # after a second
```
and should yield
```
a # after a second
b # immediately
```
=> Wait for subprocess and exit with same return code

docs/source/user-guide/reference.rst
This fixes a minor typo so that the yaml source code renders directly. See screenshot below for current version on the left, the fixed version on the right:
=> Fix small typo so default var renders correctly

anaconda_project/internal/pip_api.py
Removing `--no-deps` from pip install command to match up with user expectations around pip/conda and resolving dependencies.
cc @fpliger
=> Remove --no-deps from pip install command

anaconda_project/internal/cli/init.py, anaconda_project/internal/cli/main.py, anaconda_project/internal/cli/test/test_init.py, anaconda_project/project_ops.py, anaconda_project/test/test_project_ops.py
Sort of a fix to #148. Allows you to say
```
anaconda-project init --empty-environment
```
and start with an empty package set.
=> Add an --empty-environment flag to init

anaconda_project/env_spec.py, anaconda_project/project.py, anaconda_project/test/test_env_spec.py, anaconda_project/test/test_project_file.py, docs/source/user-guide/concepts.rst, docs/source/user-guide/reference.rst
Allows for the use of 'packages' as an alias for 'dependencies' as requested here:
https://github.com/Anaconda-Platform/anaconda-project/issues/194
=> Allow packages key

anaconda_project/env_spec.py, anaconda_project/internal/default_conda_manager.py, anaconda_project/test/test_project_ops.py
Attempts to fix #202 by creating a `conda-meta/pinned` file for all version-pinned constraints when correcting environment deficiencies. This is only used when _correcting_ an environment, not creating one for the first time.
Will have to think about how best to test this, but it is already being exercised by the code, so that's good.
=> Use pins to fix version constraint misses

anaconda_project/api.py, anaconda_project/internal/cli/main.py, anaconda_project/internal/cli/test/test_upload.py, anaconda_project/internal/cli/upload.py, anaconda_project/project_ops.py, anaconda_project/test/test_api.py
Adds `anaconda-project upload --suffix <archive-suffix>`
Only the following suffixes are allowed
* `.zip`
* `.tar.gz`
* `.tar.bz2` (default)
=> Upload zipfile; fixes issue #204

.travis.yml, anaconda_project/plugins.py, appveyor.yml
Some dependent projects depended on the misspelled class name `ArgsTrasformerTemplate`. Adding that as a synonym back in.
=> Add support for old typo

anaconda_project/internal/cli/main.py, anaconda_project/internal/cli/prepare.py, anaconda_project/internal/cli/test/test_prepare.py, anaconda_project/requirements_registry/providers/test/test_conda_env.py
This allows for the `--all` flag for prepare that will iteratively create each environment in a project yaml, given that there is more than one.
=> prepare --all

.travis.yml, anaconda_project/env_spec.py, anaconda_project/internal/default_conda_manager.py, anaconda_project/project_commands.py, anaconda_project/test/test_project.py, conda.recipe/meta.yaml
We have discovered that for later version of conda (4.6, at least), there is a conflict that occurs if the `pinned` file conflicts with an explicit historical version request. That conflict would result in a package/version pair added to the conda install command _anyway_, so there is no need for the pin at that point. So we're going to remove that pin from the file for the duration of the conda install command, and replace it once the install is complete.
=> Remove pins that are redundant w.r.t. command-line specs

anaconda_project/internal/test/tmpfile_utils.py
Still having some nagging problems with `with_directory_contents`. Specifically the previous exception tracking is not Python 2 compatible
=> Fix temporary directory issues

anaconda_project/env_spec.py, anaconda_project/internal/default_conda_manager.py, anaconda_project/test/test_project_ops.py
@AlbertDeFusco for consideration in our afternoon call.
Currently anaconda-project is creating a `pinned` file to ensure that its version specifications are enforced when new packages are added to the environment. This was necessary to address the `anaconda-project prepare` issue whereby dependency versions were allowed to change, in violation of the YAML spec. But currently the code _leaves_ the `pinned` file in place so that even direct calls to `conda` enforce those requirements.
That may be overkill for users. If so this PR would insert the `pinned` file only temporarily, after every invocation of anaconda-project's environment preparation runs, and remove it afterward.
=> Remove pins when not used

anaconda_project/internal/cli/test/test_project_load.py, anaconda_project/project.py, anaconda_project/test/test_prepare.py, anaconda_project/test/test_project.py, anaconda_project/test/test_project_ops.py
This allows the simplest anaconda-project.yml file to be utilized without an `env_specs` key.
```yaml
name: My project
packages:
- python=3.7
- notebook
channels: []
```
on `anaconda-project prepare` it will infer that the name of the `env_spec` is `default`.
=> Autogenerate default env

.coveragerc, anaconda_project/project.py, anaconda_project/test/test_project.py, appveyor.yml
I caught a problem where running `anaconda-project prepare` on the following spec would install a Python 3.8 environment. This happened because while `dependencies:` was an allowed key it was ignored.
```yaml
name: test-deps
dependencies:
- python=3.7
channels:
- defaults
env_specs:
default: {}
```
This PR also adds a test that will fail on the master branch.
=> Fix prepare action when using global "dependencies:"

anaconda_project/project_commands.py, anaconda_project/test/test_project.py, appveyor.yml, docs/source/user-guide/reference.rst, docs/source/user-guide/tasks/work-with-variables.rst
The primary goal of this PR is to highlight some pain points in the current design of `anaconda-project` and to propose one approach that makes anaconda-project more flexible for users and easier to maintain for maintainers (with an example of solving a concrete problem).
Currently anaconda-project supports three types of command: `unix`, `notebook` and `bokeh`. The `unix` command is the simplest of these, allowing any command to be run based on the string in the `anaconda-project.yml`. If any extra arguments are supplied to `anaconda-project run <command>`, these are simply appended to the command.
The `bokeh` and `notebook` commands are aimed to make two particular use cases easier. These commands run servers that need extra information (e.g allowed ports) in order to work correctly …
=> Templating for commands

setup.cfg
I noticed that tags in this repo begin with `'v'` and I guess it should be set as the tag_prefix.
=> fix versioneer tag_prefix

anaconda_project/internal/default_conda_manager.py, anaconda_project/internal/test/test_default_conda_manager.py
A-P should allow environments to be readonly as long as it does not require any changes to be made. But it expects to be able to write a timestamp file. The authors seemed to have attempted to make it fail silently if the timestamp write fails, but they didn't account for the possibility that creating the directory could fail, too.
We've created a writability test, and mark environments "unfixable" if they have deviations _and_ they are readonly. And we've discarded the requirement that the timestamp write succeeds.
=> Allow environments to be readonly if they have no deviations

conda.recipe/meta.yaml, setup.py
Title describes the full set of proposed change: `jinja2` is needed for templating introduced in #244. 
In many situations, `jinja2` is an indirect dependency (which is why the Travis and Appveyor tests passed on that PR) but in some situations (e.g `python setup.py develop` in a clean miniconda environment of Windows), `jinja2` will be unavailable. This PR makes `jinja2` an explicit dependency.
=> Declared jinja2 as a dependency in meta.yml and setup.py

anaconda_project/internal/cli/test/test_run.py, anaconda_project/project.py
@bkreider 
This allows us to run a default command (name unkonwn at runtime)
and pass arguments
> anaconda-project run default --anaconda-project-port 8086
The anaconda-project.yml file might look like
```yaml
commands:
dashboard:
unix: panel serve main.py
supports_http_options: true
api:
unix: tranquilizer api.py
supports_http_options: true
```
```
anaconda-project run default # runs panel
anaconda-project run         # runs panel
```
Even though there is not a command called "default" using the
command name default will run the first command, dashboard.
If instead a command is called "default" that will always be
as the default whether the name is included or not (this is
the original behavior and is unchanged)
```yaml
commands:
dashboard:
unix: panel serve main.py …
```
=> 'default' is an alias for the actual default command

conda.recipe/meta.yaml
The recipe on pkgs/main is noarch. Is there a reason for it *not* to be noarch in the repository as well?
=> noarch: python

.gitignore, anaconda_project/internal/cli/test/test_bundle.py, anaconda_project/local_state_file.py, anaconda_project/project.py, anaconda_project/project_file.py, anaconda_project/project_lock_file.py, anaconda_project/project_ops.py, anaconda_project/projectignore.py, anaconda_project/test/test_api.py, anaconda_project/test/test_bundler.py, anaconda_project/test/test_local_state_file.py, anaconda_project/test/test_project_file.py, anaconda_project/test/test_project_lock_file.py, anaconda_project/test/test_project_ops.py
Like git anaconda-project commands search parent directories until an `anaconda-project.yml` file is found.
The only exception is that `anaconda-project init` will *always* create a new anaconda-project.yml file in the working directory. Again, this is just like git.
=> Subdirectories in projects

.gitignore, anaconda_project/internal/cli/test/test_prepare.py, anaconda_project/internal/cli/test/test_run.py, anaconda_project/internal/conda_api.py, anaconda_project/project_commands.py, anaconda_project/test/test_project_ops.py, setup.cfg
There are now 5 places where environment variables can be set for use in `anaconda-project run`. The order listed here is highest priority first, meaning that variables set in any location override the same variable name if exists lower on the list. 
1. Command line invocation
`MY_VAR='on cli' anaconda-project run`
1. Shell export
```
MY_VAR='exported'
anaconda-project run
```
1. Set within the `anaconda-project.yml` file defined for the command to be run
```yaml
name: project-with-vars
packages:
- python=3.7
commands:
default:
variables:
MY_VAR: 'default command'
unix: env | grep MY_VAR
```
1. Set within the `anaconda-project.yml` at the top level
```yaml
name: project-with-vars
packages:
- python=3.7
variables:
MY_VAR: 'project'
commands:
default:
unix: env | grep MY_VAR
```
1. Within …
=> Add command specific variables and define variable priority order

anaconda_project/env_spec.py, anaconda_project/project_ops.py, examples/existing/.projectignore, examples/existing/anaconda-project.yml
This PR modifies the interpretation of ANACONDA_PROJECT_ENVS_PATH so that multiple environment directories can be considered. Rules:
- The variable is assumed to be a list of paths, separated by `os.pathsep`
- If an entry is empty, it is replaced with `envs`
- Relative paths are considered relative to the project directory (which is why `envs` is the appropriate default)
- If an environment with the given name does not exist anywhere on the path list, it is _created_ in the first directory.
- If the directory is outside of the project directory, it is not removed by cleanup commands.
So for example, suppose you want the default directory to still be the `envs` subdirectory, but you want to allow the child environments in your local Miniconda installation `~/miniconda3` to be considered. …
=> Allow multiple environment path directories

anaconda_project/internal/cli/prepare.py, anaconda_project/internal/cli/prepare_with_mode.py, anaconda_project/prepare.py, anaconda_project/project_ops.py, anaconda_project/requirements_registry/providers/conda_env.py, anaconda_project/test/test_api.py
I moved the `--refresh` logic—which removes the conda environment for re-creation—into the prepare step. This consolidated and simplified some of the logic. But the truth is that really the refresh logic should somehow work its way into the _requirements_ and _provider_ code. Specifically, when a refresh is requested, the requirements analysis should state that the environment needs to be re-created, and the provider should do it. But for now this is a lot closer.
=> Move the refresh logic deeper into prepare

anaconda_project/archiver.py, anaconda_project/test/test_project_ops.py
Currently it is not possible to supply an existing directory to `anaconda-project unarchive`, even if that directory is empty. AE5 works around this for now (when unpacking for a deployment), but with persistent storage for the session project we can't do that.
=> Allow unpacking into empty directory

anaconda_project/internal/default_conda_manager.py
If a prefix has a `.readonly` file in it, then anaconda-project will assume it is read-only, even if it is not. At bare minimum this is useful for testing
=> Add support for .readonly file

anaconda_project/conda_manager.py, anaconda_project/env_spec.py, anaconda_project/internal/conda_api.py, anaconda_project/internal/test/test_conda_api.py, anaconda_project/requirements_registry/providers/conda_env.py, anaconda_project/requirements_registry/providers/test/test_conda_env.py, docs/source/config.rst
to utilize read-only environments place the local envs directory (aliased as `:`) first and the read-only envs directory second.
```
export ANACONDA_PROJECT_ENVS_PATH=:/path/to/readonly/envs
anaconda-project ...
```
For all project actions the `ANACONDA_PROJECT_ENVS_PATH` paths are searched *backwards*
1. If a matching `env_spec` name is found the env is scanned for deviations
1. if there are deviations and the env is unfixable (read-only) the next `ANACONDA_PROJECT_ENVS_PATH` is checked
1. if no `env_spec` is found the env will be created in the local `envs` directory
TODO:
=> Support for read-only environments

anaconda_project/internal/conda_api.py, anaconda_project/internal/default_conda_manager.py
We currently offer the use of a `.readonly` file in the root directory of a conda environment to force anaconda-project to treat it as if it were readonly (regardless of the actual permissions). In a use case where there is an entire directory of environments where we might wish to do this, it would be nice to declare that entire directory as readonly with a single such flag file.
=> Allow .readonly flag in parent

anaconda_project/env_spec.py, anaconda_project/internal/default_conda_manager.py, anaconda_project/requirements_registry/providers/conda_env.py, anaconda_project/requirements_registry/providers/test/test_conda_env.py, docs/source/config.rst
While expanding the docs around read-only environments it occurred to me we have one more logical outcome for read-only environments: _full replacement_. This implements that, including a test
=> Add replace option for readonly handling, with docs

anaconda_project/prepare.py, anaconda_project/test/test_prepare.py
this enables `anaconda-project prepare --command default` when 'default' is an alias for the first command in the anaconda-project.yml file (see #264 )
=> support default command alias with prepare

anaconda_project/archiver.py, anaconda_project/projectignore.py, anaconda_project/test/test_bundler.py, anaconda_project/test/test_project_ops.py, docs/source/user-guide/tasks/create-project-archive.rst
Because anaconda-project respects `.gitignore` inside Git repositories there is no need to automatically create `.projectignore` if `.gitignore` is present. It is proving mildly disruptive in AE5 to create this file unnecessarily.
=> Do not create projectignore if gitignore is present

anaconda_project/api.py, anaconda_project/archiver.py, anaconda_project/conda_manager.py, anaconda_project/docker.py, anaconda_project/env_spec.py, anaconda_project/internal/cli/environment_commands.py, anaconda_project/internal/cli/main.py, anaconda_project/internal/cli/test/test_dockerize.py, anaconda_project/internal/cli/test/test_environment_commands.py, anaconda_project/internal/conda_api.py, anaconda_project/internal/default_conda_manager.py, anaconda_project/internal/pip_api.py, anaconda_project/internal/test/test_conda_api.py, anaconda_project/project_lock_file.py, anaconda_project/project_ops.py, anaconda_project/test/test_api.py, anaconda_project/test/test_docker.py, anaconda_project/test/test_project_lock_file.py, anaconda_project/test/test_project_ops.py, docs/source/config.rst, docs/source/user-guide/reference.rst, docs/source/user-guide/tasks/create-project.rst, docs/source/user-guide/tasks/work-with-commands.rst, docs/source/user-guide/tasks/work-with-packages.rst
This PR adds several pip improvements (see #181)
- displays pip install output on `anaconda-project prepare`
- displays pip packages on `anaconda-project list-packages`
- adds `anaconda-project add-packages --pip ...` to install packages and add pip packages to the yaml file
- enables full pip package locking with `anaconda-project lock`
TODO:
```yaml
name: pip-pkgs
packages:
- python=3.7
- pip:
- chardet
channels: []
env_specs:
default: {}
test:
packages:
- pip:
- requests
channels: []
platforms:
- linux-64
- osx-64
- win-64
```
```
> anaconda-project prepare
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
environment location: /Users/adefusco/Development/AnacondaPlatform/anaconda-project/examples/pip/envs/default
added / …
```
=> Enable pip package locking

anaconda_project/archiver.py, anaconda_project/test/test_project_ops.py
Zip files from Github and Gitlab have `external_attr` set to 16 for all files, which would lead `chmod` to attempt to set permission 0, which may not have a meaning.
This skips the chmod if external_attr is 16
TODO:
=> Fix extract for zipfiles from Github/Gitlab

anaconda_project/archiver.py, anaconda_project/client.py
Give it a try
```
conda install -c defusco/label/dev anaconda-project=0.10.0+4.g35774f5
```
=> progress bar for project download and extract

environment.yml, setup.py
This is a minimal fix for issue #355.  Note: after running the tests, many pieces of code were reformatted.  I did not include these changes to keep the noise at a minimum.  Should I first commit a `lint` revision with the reformatted code, then rebase my changes on top?  (If so, this could be spelled out explicitly in `CONTRIBUTING.md`.  Let me know and I can include in a future documentation PR.)
I am not comfortable enough with the project's CI to figure out why this error was not caught during CI.  Does the CI provision from an environment that uses `conda/meta.yml`?  If so, we might like to add some CI provisioning from `environment.yml` directly (for developers) and from `setup.py` (for people who install from `pip`).
=> Add tdqm dependency for progress bars.  Resolves #355.

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/main.yml, .gitignore, .vscode/launch.json, .vscode/settings.json, anaconda_project/internal/cli/test/test_service_commands.py, anaconda_project/internal/conda_api.py, anaconda_project/internal/streaming_popen.py, anaconda_project/internal/test/test_conda_api.py, anaconda_project/internal/test/test_default_conda_manager.py, anaconda_project/requirements_registry/providers/test/test_conda_env.py, anaconda_project/requirements_registry/providers/test/test_redis_provider.py, anaconda_project/test/test_env_spec.py, anaconda_project/test/test_project.py, anaconda_project/test/test_project_file.py, anaconda_project/test/test_project_lock_file.py, anaconda_project/test/test_project_ops.py, environment.yml
This adds `linux-aarch64` and `osx-arm64` as known platforms.
Further, this PR also solves #274 and allows `CONDA_SUBDIR` env var to be used to override the current platform.
For example, on an Apple M1 you can now force it to create envs for osx-64. First you'll see that Conda determines my platform is osx-arm64. I can force anaconda-project to create an osx-64 env_spec by setting `CONDA_SUBDIR=osx-64`. Otherwise the prepare would fail because Python 3.7 is not available for osx-arm64. Note that you must keep CONDA_SUBDIR set for all anaconda-project actions, not just the prepare step.
```
> conda info --json | jq .platform
"osx-arm64"
> cat anaconda-project.yml
name: arm
packages:
- python=3.7
> anaconda-project prepare
Collecting package metadata (current_repodata.json): ...working... …
```
=> Add Linux and Mac arm platforms

anaconda_project/internal/conda_api.py, anaconda_project/internal/test/test_conda_api.py, docs/source/config.rst
Enable the use of ANACONDA_PROJECT_DISABLE_OVERRIDE_CHANNELS to allow anaconda-project to respect the condarc channels definition in addition to what is written in the `channels:` key in the anaconda-project.yml file. 
The default behavior is to ignore any conda configuration of channels.
=> Disable-channel-override

CHANGELOG.md, anaconda_project/internal/conda_api.py, anaconda_project/internal/test/test_conda_api.py, docs/source/user-guide/tasks/work-with-packages.rst, setup.cfg
This addresses #387 
The "defaults" is always appended to channels: list. This is disabled by adding a dummy channel called nodefaults.
@jbednar and @jlstevens I have dev build of the implementation of nodefaults.
```
conda install -c defusco/label/dev anaconda-project=0.11.0+2
```
I am working through the current test suite and will amend it for this case as well. Here is my test:
In version 0.11.0 the following project will not prepare or lock
```yaml
name: nodefaults
channels:
- conda-forge
packages:
- python=3.8
- conda-token
- ensureconda
```
the error from 0.11.0 is 
```
The following packages are not available from current channels:
- conda-token
Current channels:
- https://conda.anaconda.org/conda-forge/osx-arm64
- https://conda.anaconda.org/conda-forge/noarch
```
Note that …
=> implicit use of "defaults" channel
